version: "3"

services:
    php:
        build:
            context: ./php # Indica onde está o arquivo Dockerfile
            dockerfile: Dockerfile
        container_name: mrb-php # Apelido para o container
        volumes:
            - ./src:/var/www/html/ # Irá copiar o conteúdo da pasta src para o container
        ports: # Mapear as portas para ficarem visiveis na máquina host
            - "80:80"
            - "443:443"
        links: # Criar conexão com o container do banco de dados
            - mysql
            - postgres

    phpmyadmin:
        build:
            context: ./phpmyadmin
            dockerfile: Dockerfile
        container_name: mrb-phpmyadmin
        restart: always
        volumes:
            - /sessions
        ports:
            - "8080:80"
        links:
            - mysql
        environment:
            - PMA_ARBITRARY=1 # Habilitando a opção para inserir host no login

    postgres:
        image: postgres:12
        container_name: mrb-pgsql
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
    mysql:
        image: mysql:5.7 # A versão 8.0 está com instabilidades
        container_name: mrb-mysql
        restart: always # Por padrão o Docker não reinicia o container, vamos mudar isso.
        volumes:
            - /var/lib/mysql
        ports:
            - "3306:3306" # Mapeei a porta para funcionar no Dbeaver, mas não precisaria.
        environment:
            - MYSQL_ROOT_PASSWORD=root # Definir senha do usuário root
            - MYSQL_DATABASE=teste # Iniciar o container com um banco criado

#-----------------------------------------------------------------------------------------------------------------------------------------------#
# Caso dê problema para seu PHP conectar ao banco, use a versão 5.7 do MySQL ou faça o tutorial abaixo:
# docker container exec -it mrb-mysql bash
# mysql -u root -p
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
#-----------------------------------------------------------------------------------------------------------------------------------------------#

